name: the-shooter
title: Fusion Arena
base: core22
version: '1.0.8'
summary: Fusion Arena Launcher
description: >
  Launcher oficial de Fusion Arena.

grade: stable
confinement: strict

apps:
  the-shooter:
    command: main

parts:
  the-shooter:
    plugin: nil
    source: .
    stage:
      - main
